### ISSUE TITLE
Unclosed regex pattern at position: 4715

### ISSUE THREAD

**Issue by CalzaFino** [tedious/JShrink#135]
Just updated to the newest version and I am getting errors during static content deployment.

The Magento 2.4.6-p1 store with pup 8.1 is showing the error:

`Error happened during deploy process: Unclosed regex pattern at position: 4715`

**Comment by emirajbbd** [comment]
RuntimeException: Unclosed regex pattern at position: 4543 in /vendor/tedivm/jshrink/src/JShrink/Minifier.php:639

 Downgrading tedivm/jshrink (v1.6.7 => v1.6.6)  fixed the issue

**Comment by eBusinessAtlantique** [comment]
It happens to me too. That is a shame that a small module from Magento 2 can stop the whole Magento. I understand people saying that Magento is heavy and unstable...

**Comment by eBusinessAtlantique** [comment]
My log :
#34 {main} {"exception":"[object] (RuntimeException(code: 0): Unclosed regex pattern at position: 755 at /home/XXX.fr/public_html/vendor/tedivm/jshrink/src/JShrink/Minifier.php:639)"} []

**Comment by tedivm** [comment]
The logs don't really help- what I need is the code that's being run through the minifier, so I can replicate the issue.

**Comment by xaevik** [comment]
@tedivm @eBusinessAtlantique downgrading to 1.6.6 or upgrading to 1.6.8 does resolve issue with Magento 2 JS minification (we just ran into this).

**Comment by hostep** [comment]
@tedivm: with version 1.6.7 we get a lot of failures on a lot of javascript files in the Magento code base.

One of them (in case it helps) is this one: https://raw.githubusercontent.com/magento/magento2/2.4.6-p1/app/code/Magento/Catalog/view/base/web/js/price-utils.js

Quick test locally after downloading that `price-utils.js` file:
```php
<?php

require_once('vendor/autoload.php');

\JShrink\Minifier::minify(
    file_get_contents('/path/to/price-utils.js')
);
```

Running this results in:
```
PHP Fatal error:  Uncaught RuntimeException: Unclosed regex pattern at position: 4894 in JShrink/src/JShrink/Minifier.php:639
Stack trace:
#0 JShrink/src/JShrink/Minifier.php(298): JShrink\Minifier->saveRegex()
#1 JShrink/src/JShrink/Minifier.php(162): JShrink\Minifier->loop()
#2 JShrink/src/JShrink/Minifier.php(137): JShrink\Minifier->minifyToString('/**\n * Copyrigh...', Array)
#3 JShrink/test.php(5): JShrink\Minifier::minify('/**\n * Copyrigh...')
#4 {main}
  thrown in JShrink/src/JShrink/Minifier.php on line 639
```

**Comment by JDavidVR** [comment]
facing same issue when adding Alpine.js ( i get the file from: https://unpkg.com/alpinejs@3.13.5/dist/cdn.min.js )

it has issues with this section:

```js
{message:"No error message given."},{el:t,expression:r}),console.warn(`Alpine Expression Error: ${e.message}

${r?'Expression: "'+r+`"

`:""}`,t),setTimeout(()=>{throw e},0)}var Ie=!0;function ke(e)
```

a them fix for me, was to change it to:

```js
{message:"No error message given."},{el:t,expression:r}),console.warn(`Alpine Expression Error: ${e.message}

${r?'Expression: "'+r+`"`:""}`,t),setTimeout(()=>{throw e},0)}var Ie=!0;function ke(e)
```
